### ISSUE TITLE
replace mongodb lol

### ISSUE THREAD

**Issue by jackharrhy** [jackharrhy/yaMUN#80]

**Comment by Mudkip** [comment]
![image](https://user-images.githubusercontent.com/4338283/113578412-5af1e980-95fd-11eb-8fcc-d45db4570799.png)

**Comment by jackharrhy** [comment]
maybe postgres, because https://jawj.github.io/zapatos/

**Comment by jackharrhy** [comment]
repo now library, issue invalid
